# NeurIPS Experiment: Gemma - Scenario 3 - Finite Lookahead
experiment_name: neurips_gemma_scenario3_finite_lookahead
seed: 42
num_seeds: 3

# Concurrency Settings
concurrent_execution: true
max_concurrent_methods: 5
api_rate_limit: 60

# Models
models:
  generation_model: "google/gemma-2-9b-it"
  evaluation_models:
    - "google/gemma-2-9b-it"
    - "meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo"

# Scenario 3: Alcohol and cigarettes ban
scenario:
  issue: "Should we ban the sale of alcohol and cigarettes in public places?"
  agent_opinions:
    Agent 1: "No we should not.  As long as adults are behaving responsibly it is for the to decide if they partake in alcohol or cigarettes.  Banning the sale of these would fundamentally change the hospitality industry and cause is the closure of businesses and loss of jobs for many people."
    Agent 2: "No we should not. More careful measures should be used to target those who engage in them in an antil social manner."
    Agent 3: "No. Even though I personally would love to see this (as a sober, non-smoker) I don't believe it would work in practice and I believe it would just drive the sale of alcohol and cigarettes underground. We can see this from looking at the prohibition era of America, even though alcohol was effectively banned, it just led to illegal saloons opening up where people would drink anyway. I think banning these things would lead to an increase in crime and the funding of criminal enterprises and organised crime."
    Agent 4: "I don't know to be honest. Cigarettes, yes, because they can cause all sorts of damage. But alcohol, I enjoy drinking and it's fun. But if we start to ban everything then we become at risk of becoming a nanny state. People should take more care for themselves and learn their own boundries."
    Agent 5: "I don't think that alcohol and cigarettes should be banned in public places but of course both should only be sold to people who are of the legal age and ID should also be retrieved. Drinking and smoking can be something that is fun if done responsibly so I dont see why it should be banned."

# Only run finite_lookahead method
methods_to_run:
  - finite_lookahead

# Method parameters for Finite Lookahead
finite_lookahead:
  branching_factor: 3  # Number of branches to explore at each step
  max_depth: [1, 2, 3]  # Maximum depth of the search tree
  max_tokens: 50  # Maximum length of the generated statement
  beta: 1.0  # Temperature parameter
  log_level: INFO  # Control logging level (e.g., DEBUG, INFO, WARNING)
  api_delay: 0.5  # Delay between API calls
  brushup: true  # Enable statement brushup
  brushup_model: "google/gemma-2-9b-it"  # Model to use for brushup (same as generation model)

# Output directory
output_dir: "results/neurips/"